services:
  # Main application container template - shows structure
  # This is overridden by stack-specific templates (stacks/python/service.yml, etc.)
  # the docker command is ran from the project root, so context is '.'
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    environment:
      # Framework environment (injected BEFORE dotenv cascade, choose the right one for your stacks)
      - APP_ENV=${APP_ENV:-development}
      - NODE_ENV=${NODE_ENV:-development}
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE:-myapp.settings}
    user: ${UID:-1000}:${GID:-1000}
    volumes:
      - .:/app                                    # ALL application code (logs auto-visible in ./var/log/)
    labels:
      - "traefik.enable=true"
      - "dev.project=${PROJECT_NAME}"
      - "traefik.http.routers.app.rule=Host(`app.${PROJECT_NAME}.localhost`)"
      - "traefik.http.routers.app.entrypoints=websecure"
      - "traefik.http.routers.app.tls=true"
      - "traefik.http.services.app.loadbalancer.server.port=8000"
    networks:
      - default

  traefik:
    image: traefik:v3.0
    # No command needed - configuration via files only
    volumes:
      # Docker socket for service discovery
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Static configuration file (API, providers, entrypoints)
      - ./docker/traefik/traefik.yaml:/etc/traefik/traefik.yaml:ro
      # Dynamic configuration file (SSL certificates, additional routes)  
      - ./docker/traefik/dynamic.yaml:/etc/traefik/dynamic.yaml:ro
      # SSL certificates generated with mkcert
      - ./docker/traefik/certs:/etc/ssl/certs:ro
      # Traefik logs directory (access.log, traefik.log)
      - ./var/log/traefik:/var/log/traefik
    ports:
      - "${EXTERNAL_HTTP_PORT:-8080}:80"           # HTTP (redirects to HTTPS)
      - "${EXTERNAL_HTTPS_PORT:-4430}:443"         # HTTPS (main traffic)
      - "${EXTERNAL_TRAEFIK_PORT:-8081}:8080"      # Dashboard
    networks:
      - default

networks:
  default:
    driver: bridge