  app:
    build: 
      context: .
      dockerfile: ./docker/app/Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    user: ${UID:-1000}:${GID:-1000}
    environment:
      # Python/Django specific environment
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE:-myapp.settings}
      - PYTHONPATH=/app
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - .:/app                                    # ALL application code (logs auto-visible in ./var/log/)
      #- ./docker/supervisord.conf:/etc/supervisor/supervisord.conf:ro  # Process config (if workers needed)
    labels:
      - "traefik.enable=true"
      - "dev.project=${PROJECT_NAME}"
      - "traefik.http.routers.app.rule=Host(`app.${PROJECT_NAME}.localhost`)"
      - "traefik.http.routers.app.entrypoints=websecure"
      - "traefik.http.routers.app.tls=true"
      - "traefik.http.services.app.loadbalancer.server.port=8000"
    networks:
      - default